name: PyGraphProfiler

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgraphviz-dev graphviz
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install setuptools wheel twine

      - name: Set PYTHONPATH
        run: export PYTHONPATH=$PYTHONPATH:/home/runner/work/pygraphprofiler/pygraphprofiler

      - name: Run tests
        env:
          PYTHONPATH: "${{ github.workspace }}"
        run: |
          python -m unittest discover -s .
          
      - name: Build distribution package
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload to PyPI
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload --skip-existing dist/*

